version: '3.3'
services:
  nginx:
    image: nginx:latest
    networks:
     - traefik-public
    logging:
      driver: json-file
    deploy:
      replicas: 2
      labels:
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.http.routers.nginx.entrypoints: websecure
        traefik.http.routers.nginx.rule: Host("web.example.com") # your actual A record
        traefik.http.routers.nginx.tls.certresolver: myresolver
        traefik.http.services.nginx.loadbalancer.server.port: '80'
networks:
  traefik-public:
    external: true
