version: '3.1'

services:
  wordpress:
    image: wordpress
    deploy:
      labels:
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.http.routers.wordpress.entrypoints: websecure
        traefik.http.routers.wordpress.rule: Host("web.example.com")
        traefik.http.routers.wordpress.tls.certresolver: myresolver
        traefik.http.services.wordpress.loadbalancer.server.port: '80'
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: db_user
      WORDPRESS_DB_PASSWORD: db_pass
      WORDPRESS_DB_NAME: db_name
    volumes:
      - wordpress:/var/www/html
    networks:
      - wp-net
      - traefik-public

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_pass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    networks:
      - wp-net

networks:
  traefik-public:
    external: true
  wp-net:
    driver: overlay

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/mnt/gfs/blog/wordpress'
  db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/mnt/gfs/blog/db'
